# Generated by Django 5.2.8 on 2025-12-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='capacidade_necessaria',
            field=models.DecimalField(decimal_places=2, help_text='Peso ou volume necessário em KG para o transporte', max_digits=10),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='cliente',
            field=models.ForeignKey(default=2, help_text='Cliente solicitante da entrega', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='core.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrega',
            name='endereco_destino',
            field=models.CharField(help_text='Endereço de destino da entrega', max_length=255),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='endereco_origem',
            field=models.CharField(help_text='Endereço de origem da entrega', max_length=255),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, help_text='Valor do frete em reais', max_digits=10),
        ),
    ]
