# Generated by Django 5.2.8 on 2025-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(help_text='CNH sem ponto ou traço', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(help_text='CPF sem ponto ou traço', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(help_text='Nome do motorista', max_length=100),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_rota', 'Em Rota'), ('inativo', 'Inativo')], default='disponivel', help_text='Status do motorista', max_length=10),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(help_text='Telefone Ex: (61) 91234-5678', max_length=20),
        ),
    ]
