# Generated by Django 5.2.8 on 2025-12-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_user_motorista_user_alter_motorista_cnh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="capacidade_maxima",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Capacidade em KG", max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veiculo",
            name="km_atual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Leitura atual do hodômetro em KM",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="modelo",
            field=models.CharField(
                default=0, help_text="Modelo e Marca (Ex: Fiat Ducato)", max_length=70
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veiculo",
            name="placa",
            field=models.CharField(
                default=0.0,
                help_text="Placa sem traços (EX: ABC1234)",
                max_length=7,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veiculo",
            name="status",
            field=models.CharField(
                choices=[
                    ("DISPONIVEL", "Disponível"),
                    ("EM_USO", "Em uso"),
                    ("MANUTENCAO", "Manutenção"),
                ],
                default="DISPONIVEL",
                help_text="Status atual do veículo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="tipo",
            field=models.CharField(
                choices=[("CARRO", "Carro"), ("VAN", "Van"), ("CAMINHAO", "Caminhão")],
                default="CARRO",
                help_text="Tipo de veículo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="motorista",
            field=models.OneToOneField(
                blank=True,
                help_text="Motorista responsável pelo veículo no momento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="veiculo",
                to="core.motorista",
            ),
        ),
    ]
