# Generated by Django 5.2.8 on 2025-12-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculo_capacidade_maxima_veiculo_km_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade_maxima',
            field=models.DecimalField(decimal_places=2, help_text='Capacidade em KG (EX: 320.00)', max_digits=10),
        ),
    ]
