# Generated by Django 5.2.8 on 2025-12-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_veiculo_capacidade_maxima"),
    ]

    operations = [
        migrations.AddField(
            model_name="rota",
            name="veiculo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rotas",
                to="core.veiculo",
            ),
            preserve_default=False,
        ),
    ]
