# Generated by Django 5.2.8 on 2025-12-17 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rota_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='capacidade_necessaria',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso ou volume necessário em KG para o transporte', max_digits=10),
        ),
        migrations.AddField(
            model_name='entrega',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente solicitante da entrega', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_entrega_prevista',
            field=models.DateTimeField(blank=True, help_text='Data e hora prevista para a entrega', null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_entrega_real',
            field=models.DateTimeField(blank=True, help_text='Data e hora real da entrega concluída', null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da solicitação da entrega', null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='endereco_destino',
            field=models.CharField(default='', help_text='Endereço de destino da entrega', max_length=255),
        ),
        migrations.AddField(
            model_name='entrega',
            name='endereco_origem',
            field=models.CharField(default='', help_text='Endereço de origem da entrega', max_length=255),
        ),
        migrations.AddField(
            model_name='entrega',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a entrega'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='rota',
            field=models.ForeignKey(blank=True, help_text='Rota associada à entrega', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='core.rota'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='pendente', help_text='Status atual da entrega', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do frete em reais', max_digits=10),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='codigo_rastreio',
            field=models.CharField(help_text='Código único de rastreamento da entrega', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='motorista',
            field=models.ForeignKey(blank=True, help_text='Motorista responsável pela entrega', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='core.motorista'),
        ),
    ]
