# Generated by Django 5.2.8 on 2025-12-12 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("modelo", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("manutencao", "Em Manutenção"),
                            ("inativo", "Inativo"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "motorista",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculo_atual",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
