# Generated by Django 5.2.8 on 2025-12-11 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        help_text="Placa sem traços (EX: ABC1234)",
                        max_length=7,
                        unique=True,
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Modelo e Marca (Ex: Fiat Ducato)", max_length=70
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CARRO", "Carro"),
                            ("VAN", "Van"),
                            ("CAMINHAO", "Caminhão"),
                        ],
                        default="CARRO",
                        help_text="Tipo de veículo",
                        max_length=20,
                    ),
                ),
                (
                    "capacidade_maxima",
                    models.DecimalField(
                        decimal_places=2, help_text="Capacidade em KG", max_digits=10
                    ),
                ),
                (
                    "km_atual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Leitura atual do hodômetro em KM",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_USO", "Em uso"),
                            ("MANUTENCAO", "Manutenção"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
                (
                    "motorista",
                    models.OneToOneField(
                        blank=True,
                        help_text="Motorista responsável pelo veículo no momento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculo_atual",
                        to="frota.motorista",
                    ),
                ),
            ],
        ),
    ]
